version: "3.8"

services:
  app:
    build:
      context: .
    init: true
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    volumes:
      - .:/var/app
    ports:
      - 8080:8080
